name: Docker Image CI for GHCR

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write   # needed to push to GHCR

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push the image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build . -t ghcr.io/neomint-research/librechatneo:latest
          docker push ghcr.io/neomint-research/librechatneo:latest